services:
  nginx:
    container_name: nginx
    image: nginx:1.29.3
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
    depends_on:
      - php
    networks:
      - social.network
  php:
    container_name: php
    build: ./docker/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - social.network
  postgres:
    container_name: postgres
    image: postgres:18.1
    environment:
      POSTGRES_DB: "social"
      POSTGRES_USER: "social"
      POSTGRES_PASSWORD: "social"
    networks:
      - social.network
networks:
  social.network:
    driver: bridge
